# -*- coding: utf-8 -*-
"""Traitement des données.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmgBNiX0YWnEKhDXA9imZweQZ6vsL0FY
"""

import pandas as pd
data = pd.read_csv("accidents.csv", sep=";", index_col=0)
data.head()

#les colonnes dont on n'a pas besoin
data = data.drop(columns=["date","original_city_code","original_name","geo_score","distance","v1","v2","pr","pr1","vosp","lartpc","larrout","env1","PR_display"])
data

data.dropna() #quand on enlève toutes les lignes qui ont des NaN dans leur colonnes , ont fini avec 1793 lignes... On pourrait utiliser un autre moyen pour les NaN

#transformer notre nouvelle data en fichier csv
data.to_csv("new_accidents.csv", index=False)



sont_identiques = data['original_city_code'] == data['current_city_code']
sont_identiques